// 題庫 — 各科目、各難度
// difficulty: 1=簡單, 2=中等, 3=困難

const QUESTIONS = {
  math: [
    // 簡單
    { q: "2 + 3 × 4 = ?", opts: ["20", "14", "24", "10"], ans: 1, diff: 1 },
    { q: "36 ÷ 6 + 5 = ?", opts: ["11", "10", "12", "9"], ans: 0, diff: 1 },
    { q: "下列哪個是質數？", opts: ["9", "15", "17", "21"], ans: 2, diff: 1 },
    { q: "三角形內角和為多少度？", opts: ["90°", "180°", "270°", "360°"], ans: 1, diff: 1 },
    { q: "5² = ?", opts: ["10", "15", "25", "50"], ans: 2, diff: 1 },
    { q: "一個正方形邊長為6，面積是多少？", opts: ["12", "24", "36", "48"], ans: 2, diff: 1 },
    { q: "|-8| = ?", opts: ["-8", "0", "8", "64"], ans: 2, diff: 1 },
    { q: "0.5 × 0.5 = ?", opts: ["0.1", "0.25", "1", "2.5"], ans: 1, diff: 1 },
    { q: "12 的因數有幾個？", opts: ["4", "5", "6", "7"], ans: 2, diff: 1 },
    { q: "4³ = ?", opts: ["12", "16", "32", "64"], ans: 3, diff: 1 },
    { q: "一個長方形長8、寬5，面積是？", opts: ["26", "40", "13", "80"], ans: 1, diff: 1 },
    { q: "下列哪個不是偶數？", opts: ["14", "22", "37", "48"], ans: 2, diff: 1 },
    { q: "15 的最大公因數（GCD）和 25 的 GCD 是？", opts: ["1", "3", "5", "15"], ans: 2, diff: 1 },
    { q: "3/4 + 1/4 = ?", opts: ["4/8", "4/4", "1", "2"], ans: 2, diff: 1 },
    { q: "一個圓的直徑為10，半徑為？", opts: ["5", "10", "20", "100"], ans: 0, diff: 1 },
    { q: "100 - 37 × 2 = ?", opts: ["26", "126", "63", "74"], ans: 0, diff: 1 },
    { q: "下列分數最大的是？", opts: ["3/5", "2/3", "5/8", "7/11"], ans: 1, diff: 1 },
    { q: "一個骰子有幾面？", opts: ["4", "5", "6", "8"], ans: 2, diff: 1 },
    { q: "7 × 8 = ?", opts: ["54", "56", "58", "64"], ans: 1, diff: 1 },
    // 中等
    { q: "√144 = ?", opts: ["11", "12", "13", "14"], ans: 1, diff: 2 },
    { q: "3x - 7 = 14，x = ?", opts: ["5", "6", "7", "8"], ans: 2, diff: 2 },
    { q: "等差數列 2, 5, 8, 11...，第10項是？", opts: ["28", "29", "30", "31"], ans: 1, diff: 2 },
    { q: "圓周率 π ≈ ?", opts: ["3.14", "3.41", "3.12", "3.21"], ans: 0, diff: 2 },
    { q: "一個圓半徑為 5，面積是？（π=3.14）", opts: ["31.4", "62.8", "78.5", "157"], ans: 2, diff: 2 },
    { q: "2³ + 3² = ?", opts: ["13", "17", "25", "35"], ans: 1, diff: 2 },
    { q: "x² = 25 時，x 的正數解為？", opts: ["4", "5", "6", "7"], ans: 1, diff: 2 },
    { q: "下列哪個是完全平方數？", opts: ["50", "72", "81", "90"], ans: 2, diff: 2 },
    { q: "一個梯形上底4、下底8、高5，面積是？", opts: ["25", "30", "60", "20"], ans: 1, diff: 2 },
    { q: "2/3 ÷ 4/9 = ?", opts: ["8/27", "3/2", "2/9", "6/12"], ans: 1, diff: 2 },
    { q: "等比數列 3, 6, 12...，第5項是？", opts: ["24", "36", "48", "96"], ans: 2, diff: 2 },
    { q: "一元二次方程式 x²-5x+6=0 的解為？", opts: ["1,6", "2,3", "-2,-3", "1,5"], ans: 1, diff: 2 },
    { q: "0! = ?", opts: ["0", "1", "未定義", "無限大"], ans: 1, diff: 2 },
    { q: "一個正六邊形的內角各為幾度？", opts: ["90°", "108°", "120°", "135°"], ans: 2, diff: 2 },
    // 困難
    { q: "若 f(x)=2x²-3x+1，f(2)=？", opts: ["1", "2", "3", "4"], ans: 2, diff: 3 },
    { q: "1 + 2 + 3 + ... + 100 = ?", opts: ["4950", "5000", "5050", "5100"], ans: 2, diff: 3 },
    { q: "直角三角形兩股為 3、4，斜邊為？", opts: ["4", "5", "6", "7"], ans: 1, diff: 3 },
    { q: "(a+b)²展開等於？", opts: ["a²+b²", "a²+ab+b²", "a²+2ab+b²", "2a²+2b²"], ans: 2, diff: 3 },
    { q: "sin 30° = ?", opts: ["1/2", "√2/2", "√3/2", "1"], ans: 0, diff: 3 },
    { q: "下列哪個是無理數？", opts: ["0.5", "√4", "√2", "3/7"], ans: 2, diff: 3 },
    { q: "等差數列前n項和公式為？", opts: ["na₁", "n(a₁+aₙ)/2", "n²a₁", "naₙ/2"], ans: 1, diff: 3 },
    { q: "log₂(8) = ?", opts: ["2", "3", "4", "8"], ans: 1, diff: 3 },
    { q: "等差數列 -3, 1, 5, 9...，前10項的和是？", opts: ["150", "155", "160", "165"], ans: 0, diff: 3 },
    // 新增簡單
    { q: "一個正三角形邊長為6，周長是？", opts: ["12", "18", "24", "36"], ans: 1, diff: 1 },
    { q: "下列哪個是合數？", opts: ["2", "5", "7", "9"], ans: 3, diff: 1 },
    { q: "3/5 用小數表示是？", opts: ["0.3", "0.5", "0.6", "0.8"], ans: 2, diff: 1 },
    { q: "兩個相鄰整數，差為？", opts: ["0", "1", "2", "不一定"], ans: 1, diff: 1 },
    { q: "60 分鐘 = 幾小時？", opts: ["0.5", "1", "1.5", "2"], ans: 1, diff: 1 },
    // 新增中等
    { q: "2x + 6 = 18，x = ?", opts: ["3", "4", "6", "12"], ans: 2, diff: 2 },
    { q: "三角形內角比為 1:2:3，最大角幾度？", opts: ["60°", "90°", "120°", "45°"], ans: 1, diff: 2 },
    { q: "下列哪個是一次函數？", opts: ["y=x²", "y=2x+1", "y=1/x", "y=√x"], ans: 1, diff: 2 },
    { q: "圓柱體積公式為？", opts: ["πr²h", "2πrh", "πr³", "4/3πr³"], ans: 0, diff: 2 },
    { q: "4! = ?", opts: ["8", "16", "24", "32"], ans: 2, diff: 2 },
    // 新增困難
    { q: "若 a+b=5, ab=6，則 a²+b² = ?", opts: ["13", "25", "12", "19"], ans: 0, diff: 3 },
    { q: "解不等式 3x-2 > 7，x 的範圍是？", opts: ["x>1", "x>2", "x>3", "x>5"], ans: 2, diff: 3 },
    { q: "sin²θ + cos²θ = ?", opts: ["0", "1", "2", "不確定"], ans: 1, diff: 3 },
    // 國中二年級下學期
    { q: "√9 = ?", opts: ["2", "3", "4", "9"], ans: 1, diff: 1 },
    { q: "a²-b² 因式分解等於？", opts: ["(a-b)²", "(a+b)(a-b)", "(a+b)²", "a(a-b)"], ans: 1, diff: 1 },
    { q: "坐標點 (3,-2) 在第幾象限？", opts: ["第一象限", "第二象限", "第三象限", "第四象限"], ans: 3, diff: 1 },
    { q: "x² = 16 的正數解為？", opts: ["4", "8", "16", "256"], ans: 0, diff: 1 },
    { q: "兩直線平行時，同位角關係為？", opts: ["互補", "互餘", "相等", "無關"], ans: 2, diff: 1 },
    { q: "√2 的近似值約為？", opts: ["1.232", "1.414", "1.618", "1.732"], ans: 1, diff: 1 },
    { q: "(x+3)² 展開等於？", opts: ["x²+9", "x²+3x+9", "x²+6x+9", "x²+6x+6"], ans: 2, diff: 1 },
    { q: "x²-5x+6=0 的兩根為？", opts: ["2和3", "1和6", "2和-3", "-2和3"], ans: 0, diff: 2 },
    { q: "(2x+1)(2x-1) 展開等於？", opts: ["4x²-1", "4x²+1", "4x²-4x-1", "2x²-1"], ans: 0, diff: 2 },
    { q: "因式分解 x²-9 = ?", opts: ["(x-3)²", "(x+3)(x-3)", "(x-9)(x+1)", "x(x-9)"], ans: 1, diff: 2 },
    { q: "函數 y=-2x+4，x=1 時 y=？", opts: ["2", "6", "4", "-2"], ans: 0, diff: 2 },
    { q: "三角形三邊 7、24、25，這是什麼三角形？", opts: ["銳角三角形", "鈍角三角形", "直角三角形", "等腰三角形"], ans: 2, diff: 2 },
    { q: "x²+6x+9 因式分解 = ?（完全平方式）", opts: ["(x+3)²", "(x-3)²", "(x+9)²", "(x+6)²"], ans: 0, diff: 2 },
    { q: "一元二次方程式的一般式為？", opts: ["ax+b=0", "ax²+bx+c=0", "ax³+b=0", "a/x+b=0"], ans: 1, diff: 2 },
    { q: "√3 × √3 = ?", opts: ["√6", "3", "6", "9"], ans: 1, diff: 2 },
    { q: "判別式 b²-4ac > 0 表示方程式有？", opts: ["無實數解", "一個重根", "兩個相異實根", "虛數解"], ans: 2, diff: 3 },
    { q: "因式分解 3x²-12 = ?", opts: ["3(x-2)²", "3(x+2)(x-2)", "(3x+6)(x-2)", "3x(x-4)"], ans: 1, diff: 3 },
    { q: "二次函數 y=x²-4x+3，頂點的 x 坐標為？", opts: ["1", "2", "3", "4"], ans: 1, diff: 3 },
    { q: "√75 化簡等於？", opts: ["5√3", "3√5", "15√3", "5√15"], ans: 0, diff: 3 },
    { q: "x²-2x-8=0 的解為？", opts: ["4或-2", "2或4", "-4或2", "8或-1"], ans: 0, diff: 3 },
  ],

  english: [
    // 簡單
    { q: "Which word means 'fast'?", opts: ["Slow", "Quick", "Quiet", "Dark"], ans: 1, diff: 1 },
    { q: "「圖書館」的英文是？", opts: ["Library", "Laundry", "Lottery", "Laboratory"], ans: 0, diff: 1 },
    { q: "He ___ to school every day.", opts: ["go", "goes", "going", "gone"], ans: 1, diff: 1 },
    { q: "「beautiful」的中文意思是？", opts: ["美麗的", "快樂的", "聰明的", "強壯的"], ans: 0, diff: 1 },
    { q: "Which is a vegetable?", opts: ["Apple", "Banana", "Carrot", "Grape"], ans: 2, diff: 1 },
    { q: "「telephone」的中文是？", opts: ["電視", "電話", "電腦", "電燈"], ans: 1, diff: 1 },
    { q: "12 months = 1 ___", opts: ["Week", "Day", "Year", "Century"], ans: 2, diff: 1 },
    { q: "「hospital」的中文是？", opts: ["學校", "飯店", "醫院", "工廠"], ans: 2, diff: 1 },
    { q: "What color is the sky?", opts: ["Green", "Red", "Blue", "Yellow"], ans: 2, diff: 1 },
    { q: "星期三的英文是？", opts: ["Monday", "Tuesday", "Wednesday", "Thursday"], ans: 2, diff: 1 },
    { q: "Which is an animal?", opts: ["Table", "Chair", "Tiger", "River"], ans: 2, diff: 1 },
    { q: "「delicious」最接近的意思是？", opts: ["好吃的", "漂亮的", "危險的", "安靜的"], ans: 0, diff: 1 },
    { q: "We ___ happy yesterday.", opts: ["are", "is", "were", "be"], ans: 2, diff: 1 },
    { q: "「butterfly」的中文是？", opts: ["蜜蜂", "螞蟻", "蝴蝶", "蜻蜓"], ans: 2, diff: 1 },
    { q: "Which is NOT a season?", opts: ["Spring", "Winter", "October", "Summer"], ans: 2, diff: 1 },
    { q: "「勇敢的」的英文是？", opts: ["brave", "cave", "wave", "gave"], ans: 0, diff: 1 },
    // 中等
    { q: "She ___ studying when I called.", opts: ["is", "was", "were", "be"], ans: 1, diff: 2 },
    { q: "The opposite of 'difficult' is?", opts: ["Hard", "Tough", "Easy", "Complex"], ans: 2, diff: 2 },
    { q: "I have lived here ___ 5 years.", opts: ["since", "for", "ago", "before"], ans: 1, diff: 2 },
    { q: "Which is NOT a pronoun?", opts: ["He", "She", "Run", "They"], ans: 2, diff: 2 },
    { q: "「approximately」的中文意思是？", opts: ["絕對地", "大約地", "偶爾地", "永遠地"], ans: 1, diff: 2 },
    { q: "The book is ___ than I expected.", opts: ["more interesting", "most interesting", "interestinger", "interest"], ans: 0, diff: 2 },
    { q: "She ___ the piano since age 6.", opts: ["plays", "played", "has played", "is playing"], ans: 2, diff: 2 },
    { q: "Which sentence is correct?", opts: ["He don't like it.", "He doesn't likes it.", "He doesn't like it.", "He not like it."], ans: 2, diff: 2 },
    { q: "「Ambitious」的意思是？", opts: ["懶惰的", "膽怯的", "有抱負的", "誠實的"], ans: 2, diff: 2 },
    { q: "___ you mind closing the window?", opts: ["Will", "Would", "Should", "Could"], ans: 1, diff: 2 },
    { q: "What is the plural of 'mouse'?", opts: ["mouses", "mices", "mice", "mouse"], ans: 2, diff: 2 },
    { q: "They ___ watching TV when the power went out.", opts: ["are", "were", "was", "be"], ans: 1, diff: 2 },
    { q: "「猶豫」的英文是？", opts: ["hesitate", "celebrate", "navigate", "investigate"], ans: 0, diff: 2 },
    // 困難
    { q: "If I ___ rich, I would travel the world.", opts: ["am", "was", "were", "be"], ans: 2, diff: 3 },
    { q: "「Perseverance」means?", opts: ["Laziness", "Persistence", "Pleasure", "Patience"], ans: 1, diff: 3 },
    { q: "The book ___ by the author last year.", opts: ["write", "writes", "was written", "is writing"], ans: 2, diff: 3 },
    { q: "Synonym of 'magnificent'?", opts: ["Tiny", "Splendid", "Dull", "Ordinary"], ans: 1, diff: 3 },
    { q: "Not only ___ he smart, but also kind.", opts: ["is", "was", "are", "were"], ans: 0, diff: 3 },
    { q: "「Ephemeral」means?", opts: ["Permanent", "Short-lived", "Ancient", "Massive"], ans: 1, diff: 3 },
    { q: "Had I known earlier, I ___ helped.", opts: ["would have", "will have", "would", "could"], ans: 0, diff: 3 },
    { q: "「Serendipity」means?", opts: ["Sadness", "A happy accident", "Determination", "Confusion"], ans: 1, diff: 3 },
    { q: "「Ubiquitous」means?", opts: ["Unique", "Everywhere", "Unusual", "Underground"], ans: 1, diff: 3 },
    // 新增簡單
    { q: "「橘子」的英文是？", opts: ["Lemon", "Orange", "Apple", "Grape"], ans: 1, diff: 1 },
    { q: "「圖書館」的英文是？", opts: ["Restaurant", "Hospital", "Library", "Museum"], ans: 2, diff: 1 },
    { q: "Which number comes after twelve?", opts: ["10", "11", "13", "14"], ans: 2, diff: 1 },
    { q: "「帽子」的英文是？", opts: ["Coat", "Hat", "Shoe", "Sock"], ans: 1, diff: 1 },
    { q: "I ___ a student.", opts: ["is", "am", "are", "be"], ans: 1, diff: 1 },
    // 新增中等
    { q: "We ___ finish the project by tomorrow.", opts: ["must", "can", "should", "ought"], ans: 0, diff: 2 },
    { q: "「Generous」的中文意思是？", opts: ["吝嗇的", "慷慨的", "勤勞的", "謙虛的"], ans: 1, diff: 2 },
    { q: "Neither he nor she ___ ready.", opts: ["are", "is", "were", "am"], ans: 1, diff: 2 },
    { q: "What is the past tense of 'fly'?", opts: ["flied", "flew", "flown", "flying"], ans: 1, diff: 2 },
    // 新增困難
    { q: "「Ambivalent」means?", opts: ["Very confident", "Having mixed feelings", "Fully committed", "Completely happy"], ans: 1, diff: 3 },
    { q: "The harder she works, ___ she succeeds.", opts: ["the more", "the most", "more", "most"], ans: 0, diff: 3 },
    { q: "「Loquacious」means?", opts: ["Silent", "Very talkative", "Intelligent", "Mysterious"], ans: 1, diff: 3 },
    // 國中二年級下學期
    { q: "「環境」的英文是？", opts: ["environment", "entertainment", "enthusiasm", "endurance"], ans: 0, diff: 1 },
    { q: "She is taller ___ her sister.", opts: ["then", "than", "that", "those"], ans: 1, diff: 1 },
    { q: "「成就」的英文是？", opts: ["achievement", "adventure", "agreement", "argument"], ans: 0, diff: 1 },
    { q: "「污染」的英文是？", opts: ["pollution", "solution", "evolution", "revolution"], ans: 0, diff: 1 },
    { q: "He is the man ___ saved my life.", opts: ["which", "what", "who", "whom"], ans: 2, diff: 1 },
    { q: "I have already ___ my homework.", opts: ["finish", "finishes", "finished", "finishing"], ans: 2, diff: 1 },
    { q: "「科技」的英文是？", opts: ["technology", "ecology", "geology", "biology"], ans: 0, diff: 1 },
    { q: "They have lived here ___ 2010.", opts: ["for", "since", "ago", "during"], ans: 1, diff: 2 },
    { q: "The letter was written ___ him.", opts: ["by", "for", "with", "to"], ans: 0, diff: 2 },
    { q: "This is the book ___ I told you about.", opts: ["who", "whom", "which", "whose"], ans: 2, diff: 2 },
    { q: "She suggested ___ early.", opts: ["leaving", "to leave", "leave", "left"], ans: 0, diff: 2 },
    { q: "I enjoy ___ music.", opts: ["listen to", "listening to", "to listen", "listened to"], ans: 1, diff: 2 },
    { q: "The movie ___ by millions of people.", opts: ["was watched", "watched", "is watching", "watches"], ans: 0, diff: 2 },
    { q: "He is smart enough ___ the problem.", opts: ["solve", "solving", "to solve", "solved"], ans: 2, diff: 2 },
    { q: "___ he nor his friends were at the party.", opts: ["Either", "Both", "Neither", "Each"], ans: 2, diff: 2 },
    { q: "「Deteriorate」的意思是？", opts: ["改善", "惡化", "穩定", "消失"], ans: 1, diff: 3 },
    { q: "The book, ___ was published last year, became a bestseller.", opts: ["that", "which", "who", "what"], ans: 1, diff: 3 },
    { q: "She ___ for hours before she found her keys.", opts: ["searched", "was searching", "had been searching", "has searched"], ans: 2, diff: 3 },
    { q: "Not until she arrived ___ he leave.", opts: ["did", "does", "was", "has"], ans: 0, diff: 3 },
    { q: "Having ___ the exam, she felt relieved.", opts: ["passed", "pass", "passing", "to pass"], ans: 0, diff: 3 },
  ],

  science: [
    // 簡單
    { q: "水的化學式是？", opts: ["CO₂", "H₂O", "O₂", "H₂"], ans: 1, diff: 1 },
    { q: "植物進行光合作用需要什麼？", opts: ["氧氣", "二氧化碳", "氮氣", "氫氣"], ans: 1, diff: 1 },
    { q: "人體最大的器官是？", opts: ["心臟", "肺臟", "皮膚", "肝臟"], ans: 2, diff: 1 },
    { q: "聲音在哪種介質中傳播最快？", opts: ["空氣", "水", "真空", "固體"], ans: 3, diff: 1 },
    { q: "地球繞太陽公轉一圈約需多少天？", opts: ["180天", "265天", "365天", "400天"], ans: 2, diff: 1 },
    { q: "電池的兩端分別是什麼？", opts: ["正極和負極", "左極和右極", "上極和下極", "內極和外極"], ans: 0, diff: 1 },
    { q: "下列哪種是植物？", opts: ["珊瑚", "海葵", "水草", "水母"], ans: 2, diff: 1 },
    { q: "空氣中含量最多的氣體是？", opts: ["氧氣", "二氧化碳", "氮氣", "氫氣"], ans: 2, diff: 1 },
    { q: "鑽石的主要成分是？", opts: ["矽", "碳", "鐵", "鈣"], ans: 1, diff: 1 },
    { q: "月球繞地球公轉一圈約需多少天？", opts: ["7天", "14天", "27天", "365天"], ans: 2, diff: 1 },
    { q: "下列哪個是可再生能源？", opts: ["煤炭", "石油", "天然氣", "太陽能"], ans: 3, diff: 1 },
    { q: "光合作用主要在植物哪個部位進行？", opts: ["根部", "莖部", "葉綠體", "細胞核"], ans: 2, diff: 1 },
    { q: "地震的強度通常用什麼衡量？", opts: ["分貝", "里氏規模", "帕斯卡", "焦耳"], ans: 1, diff: 1 },
    { q: "冰的密度比水___。", opts: ["大", "小", "相等", "不確定"], ans: 1, diff: 1 },
    // 中等
    { q: "下列哪種物質是鹼性？", opts: ["醋", "檸檬汁", "小蘇打水", "鹽酸"], ans: 2, diff: 2 },
    { q: "DNA 位在細胞的哪個部位？", opts: ["細胞膜", "細胞質", "細胞核", "粒線體"], ans: 2, diff: 2 },
    { q: "光在真空中的速度約為？", opts: ["3×10⁶ m/s", "3×10⁸ m/s", "3×10¹⁰ m/s", "3×10⁴ m/s"], ans: 1, diff: 2 },
    { q: "元素週期表中，氫的原子序是？", opts: ["0", "1", "2", "8"], ans: 1, diff: 2 },
    { q: "下列哪種力讓月球繞地球轉？", opts: ["磁力", "摩擦力", "萬有引力", "靜電力"], ans: 2, diff: 2 },
    { q: "食物中提供熱量的三大營養素不包含？", opts: ["醣類", "脂肪", "蛋白質", "維生素"], ans: 3, diff: 2 },
    { q: "下列哪個是化學變化？", opts: ["水結冰", "紙張燃燒", "鐵塊切割", "糖溶於水"], ans: 1, diff: 2 },
    { q: "人體血型系統中，何種血型稱為「萬能供血者」？", opts: ["A型", "B型", "AB型", "O型"], ans: 3, diff: 2 },
    { q: "牛頓第一運動定律又稱為？", opts: ["重力定律", "慣性定律", "加速度定律", "作用力定律"], ans: 1, diff: 2 },
    { q: "地球磁場的北磁極位於地理上的哪個方向？", opts: ["北方", "南方", "東方", "西方"], ans: 1, diff: 2 },
    { q: "人體共有幾對染色體？", opts: ["20對", "21對", "23對", "24對"], ans: 2, diff: 2 },
    { q: "下列哪個元素是惰性氣體？", opts: ["氫（H）", "氮（N）", "氦（He）", "氟（F）"], ans: 2, diff: 2 },
    { q: "地球距離太陽約多遠？", opts: ["1.5千萬公里", "1.5億公里", "15億公里", "1.5兆公里"], ans: 1, diff: 2 },
    // 困難
    { q: "光合作用的方程式：6CO₂ + 6H₂O → ?", opts: ["6O₂+C₆H₁₂O₆", "H₂O₂+O₂", "CO+H₂", "CH₄+O₂"], ans: 0, diff: 3 },
    { q: "牛頓第二運動定律：F = ?", opts: ["m+a", "m-a", "ma", "m/a"], ans: 2, diff: 3 },
    { q: "下列哪個是非金屬元素？", opts: ["Fe（鐵）", "Cu（銅）", "S（硫）", "Al（鋁）"], ans: 2, diff: 3 },
    { q: "人體血液中，氧氣主要由什麼攜帶？", opts: ["血漿", "白血球", "血小板", "血紅素"], ans: 3, diff: 3 },
    { q: "電功率的計算公式是？", opts: ["P=IV", "P=I/V", "P=V/I", "P=I+V"], ans: 0, diff: 3 },
    { q: "下列哪個粒子帶負電？", opts: ["質子", "中子", "電子", "原子核"], ans: 2, diff: 3 },
    { q: "孟德爾遺傳定律中，顯性基因以何表示？", opts: ["小寫字母", "大寫字母", "數字", "符號"], ans: 1, diff: 3 },
    { q: "黑洞的逃脫速度超過哪個速度？", opts: ["音速", "光速", "聲速的10倍", "地球第一宇宙速度"], ans: 1, diff: 3 },
    // 新增簡單
    { q: "水在幾度C會結冰？", opts: ["-10°C", "0°C", "4°C", "10°C"], ans: 1, diff: 1 },
    { q: "人類呼吸吸入的主要氣體是？", opts: ["氮氣", "二氧化碳", "氧氣", "氫氣"], ans: 2, diff: 1 },
    { q: "下列哪種動物是哺乳類？", opts: ["青蛙", "鮭魚", "鯨魚", "鱷魚"], ans: 2, diff: 1 },
    { q: "植物的根主要功能是？", opts: ["光合作用", "吸水與固定", "製造種子", "呼吸作用"], ans: 1, diff: 1 },
    { q: "太陽系中最大的行星是？", opts: ["土星", "天王星", "木星", "海王星"], ans: 2, diff: 1 },
    // 新增中等
    { q: "原子中，帶正電的粒子是？", opts: ["電子", "中子", "質子", "光子"], ans: 2, diff: 2 },
    { q: "下列哪種反應屬於吸熱反應？", opts: ["燃燒", "氧化生鏽", "光合作用", "爆炸"], ans: 2, diff: 2 },
    { q: "電阻的單位是？", opts: ["安培", "伏特", "歐姆", "瓦特"], ans: 2, diff: 2 },
    { q: "月球表面為什麼沒有大氣層？", opts: ["距地球太近", "溫度太高", "質量太小引力不足", "被太陽風吹走"], ans: 2, diff: 2 },
    // 新增困難
    { q: "細胞的能量工廠是？", opts: ["細胞核", "內質網", "粒線體", "高爾基體"], ans: 2, diff: 3 },
    { q: "DNA 雙股螺旋中，腺嘌呤(A)配對的鹼基是？", opts: ["胞嘧啶(C)", "鳥嘌呤(G)", "胸腺嘧啶(T)", "尿嘧啶(U)"], ans: 2, diff: 3 },
    { q: "歐姆定律公式：I = ?", opts: ["V×R", "V/R", "R/V", "V+R"], ans: 1, diff: 3 },
    // 國中二年級下學期
    { q: "光的反射定律：入射角___反射角", opts: ["大於", "等於", "小於", "無關"], ans: 1, diff: 1 },
    { q: "燈泡發光是將電能轉換為？", opts: ["化學能", "熱能和光能", "機械能", "聲能"], ans: 1, diff: 1 },
    { q: "酸性溶液的 pH 值小於？", opts: ["5", "6", "7", "8"], ans: 2, diff: 1 },
    { q: "並聯電路中，各支路電壓？", opts: ["不同", "相等", "為零", "不確定"], ans: 1, diff: 1 },
    { q: "光在水中的速度比在空氣中？", opts: ["快", "慢", "相等", "不一定"], ans: 1, diff: 1 },
    { q: "食鹽（NaCl）溶於水呈？", opts: ["酸性", "鹼性", "中性", "不確定"], ans: 2, diff: 1 },
    { q: "遺傳物質 DNA 是由什麼單體組成？", opts: ["胺基酸", "核苷酸", "葡萄糖", "脂肪酸"], ans: 1, diff: 1 },
    { q: "光從空氣進入水中，折射角___入射角", opts: ["大於", "等於", "小於", "無關"], ans: 2, diff: 2 },
    { q: "串聯電路中，各電阻的電流？", opts: ["不同", "相等", "與電阻成正比", "與電壓成反比"], ans: 1, diff: 2 },
    { q: "鹽酸（HCl）與氫氧化鈉（NaOH）反應產生？", opts: ["水和氧氣", "水和食鹽", "食鹽和氫氣", "水和鹽酸"], ans: 1, diff: 2 },
    { q: "顯性基因「Aa」，個體表現型為？", opts: ["隱性", "顯性", "介於中間", "不確定"], ans: 1, diff: 2 },
    { q: "凸透鏡可以使光線？", opts: ["發散", "聚焦", "全反射", "吸收"], ans: 1, diff: 2 },
    { q: "兩個電池串聯，總電壓如何變化？", opts: ["不變", "疊加增大", "減半", "只保留較大的"], ans: 1, diff: 2 },
    { q: "銅（Cu）加熱後與氧反應生成？", opts: ["CuO", "Cu₂O₂", "CuO₂", "Cu₂O"], ans: 0, diff: 2 },
    { q: "下列哪種試劑可測試酸鹼性？", opts: ["硝酸銀", "石蕊試紙", "碘液", "本尼迪特試劑"], ans: 1, diff: 2 },
    { q: "人類體細胞共有幾條染色體？", opts: ["23條", "46條", "44條", "48條"], ans: 1, diff: 3 },
    { q: "光的全反射發生在光從？", opts: ["空氣進入水", "水進入空氣且入射角大於臨界角", "任何兩種介質之間", "水進入玻璃"], ans: 1, diff: 3 },
    { q: "電阻 R₁=3Ω, R₂=6Ω 並聯，總電阻為？", opts: ["9Ω", "3Ω", "2Ω", "18Ω"], ans: 2, diff: 3 },
    { q: "孟德爾豌豆實驗，Aa × Aa 後代顯性:隱性比例為？", opts: ["1:1", "3:1", "2:1", "1:3"], ans: 1, diff: 3 },
    { q: "碳酸鈉（Na₂CO₃）水溶液呈？", opts: ["酸性", "中性", "鹼性", "不確定"], ans: 2, diff: 3 },
  ],

  history: [
    // 簡單
    { q: "台灣光復是哪一年？", opts: ["1943", "1945", "1947", "1949"], ans: 1, diff: 1 },
    { q: "中華民國憲法在哪一年公布實施？", opts: ["1945", "1946", "1947", "1948"], ans: 2, diff: 1 },
    { q: "鄭成功來台趕走哪個國家的勢力？", opts: ["葡萄牙", "西班牙", "荷蘭", "英國"], ans: 2, diff: 1 },
    { q: "世界上最早發明印刷術的是哪個民族？", opts: ["埃及人", "羅馬人", "中國人", "希臘人"], ans: 2, diff: 1 },
    { q: "秦始皇統一中國是哪一年？", opts: ["前500年", "前300年", "前221年", "前100年"], ans: 2, diff: 1 },
    { q: "台灣最早的原住民族屬於哪個語系？", opts: ["印歐語系", "南島語系", "漢藏語系", "阿爾泰語系"], ans: 1, diff: 1 },
    { q: "聯合國成立於哪一年？", opts: ["1941", "1943", "1945", "1947"], ans: 2, diff: 1 },
    { q: "古希臘的民主政治發源地是？", opts: ["斯巴達", "雅典", "科林斯", "底比斯"], ans: 1, diff: 1 },
    { q: "古羅馬帝國的首都是？", opts: ["雅典", "迦太基", "羅馬", "君士坦丁堡"], ans: 2, diff: 1 },
    { q: "孔子是哪個時代的人？", opts: ["夏朝", "商朝", "春秋時代", "秦朝"], ans: 2, diff: 1 },
    { q: "日本在哪一年宣布二戰投降？", opts: ["1943", "1944", "1945", "1946"], ans: 2, diff: 1 },
    // 中等
    { q: "工業革命最早發生在哪個國家？", opts: ["法國", "德國", "美國", "英國"], ans: 3, diff: 2 },
    { q: "下列哪位是文藝復興時期的藝術家？", opts: ["牛頓", "達文西", "愛因斯坦", "馬可波羅"], ans: 1, diff: 2 },
    { q: "第一次世界大戰起始於哪一年？", opts: ["1912", "1914", "1916", "1918"], ans: 1, diff: 2 },
    { q: "古埃及的金字塔主要用途是？", opts: ["倉庫", "神廟", "陵墓", "天文台"], ans: 2, diff: 2 },
    { q: "「絲路」連接中國與哪個地區？", opts: ["非洲", "歐洲與中亞", "東南亞", "美洲"], ans: 1, diff: 2 },
    { q: "鴉片戰爭後，清朝與英國簽訂了哪個條約？", opts: ["北京條約", "南京條約", "馬關條約", "天津條約"], ans: 1, diff: 2 },
    { q: "法國大革命發生於哪一年？", opts: ["1688", "1776", "1789", "1848"], ans: 2, diff: 2 },
    { q: "「文藝復興」最早從哪個城市興起？", opts: ["巴黎", "威尼斯", "佛羅倫斯", "羅馬"], ans: 2, diff: 2 },
    { q: "美國宣布獨立於哪一年？", opts: ["1774", "1776", "1778", "1780"], ans: 1, diff: 2 },
    { q: "台灣在哪一年正式加入WTO？", opts: ["1995", "2000", "2002", "2005"], ans: 2, diff: 2 },
    // 困難
    { q: "馬關條約簽訂後，台灣割讓給哪個國家？", opts: ["英國", "美國", "日本", "俄國"], ans: 2, diff: 3 },
    { q: "法國大革命的口號不包含哪項？", opts: ["自由", "平等", "民主", "博愛"], ans: 2, diff: 3 },
    { q: "「布列頓森林體系」確立了哪種貨幣為國際準備貨幣？", opts: ["英鎊", "法郎", "美元", "馬克"], ans: 2, diff: 3 },
    { q: "冷戰期間，北大西洋公約組織（NATO）成立於？", opts: ["1945", "1947", "1949", "1955"], ans: 2, diff: 3 },
    { q: "「光榮革命」發生在哪個國家？", opts: ["法國", "英國", "美國", "德國"], ans: 1, diff: 3 },
    { q: "甲午戰爭（中日甲午戰爭）發生在哪一年？", opts: ["1884", "1894", "1904", "1914"], ans: 1, diff: 3 },
    // 新增簡單
    { q: "台灣位於哪個大洲？", opts: ["非洲", "歐洲", "亞洲", "美洲"], ans: 2, diff: 1 },
    { q: "長城是哪個朝代修建的？", opts: ["漢朝", "唐朝", "明朝", "清朝"], ans: 2, diff: 1 },
    { q: "第二次世界大戰結束於哪一年？", opts: ["1943", "1944", "1945", "1946"], ans: 2, diff: 1 },
    { q: "美國在哪個城市遭受1941年偷襲？", opts: ["關島", "珍珠港", "沖繩", "菲律賓"], ans: 1, diff: 1 },
    { q: "台灣海峽隔開台灣與哪個地方？", opts: ["日本", "韓國", "中國大陸", "菲律賓"], ans: 2, diff: 1 },
    // 新增中等
    { q: "下列哪位是中國四大發明之一的發明者相關人物？", opts: ["蔡倫（造紙）", "瓦特（蒸汽機）", "牛頓（萬有引力）", "愛迪生（電燈）"], ans: 0, diff: 2 },
    { q: "台灣民主化過程中，首次總統直選是哪一年？", opts: ["1988", "1992", "1996", "2000"], ans: 2, diff: 2 },
    { q: "「新航路開闢」後，哪個國家最早到達印度？", opts: ["西班牙", "葡萄牙", "英國", "荷蘭"], ans: 1, diff: 2 },
    { q: "春秋戰國時期「百家爭鳴」不包含哪個學派？", opts: ["儒家", "道家", "佛家", "法家"], ans: 2, diff: 2 },
    // 新增困難
    { q: "台灣二二八事件發生於哪一年？", opts: ["1945", "1946", "1947", "1948"], ans: 2, diff: 3 },
    { q: "「凡爾賽條約」簽訂於哪一年，結束了一戰？", opts: ["1917", "1918", "1919", "1920"], ans: 2, diff: 3 },
    { q: "「明治維新」是哪個國家的近代化改革？", opts: ["中國", "韓國", "日本", "越南"], ans: 2, diff: 3 },
    // 國中二年級下學期
    { q: "台灣最高峰是？", opts: ["雪山", "合歡山", "玉山", "阿里山"], ans: 2, diff: 1 },
    { q: "日本統治台灣始於哪一年？", opts: ["1894年", "1895年", "1900年", "1911年"], ans: 1, diff: 1 },
    { q: "憲法保障的基本人權不包含？", opts: ["言論自由", "集會自由", "傷害他人的自由", "信仰自由"], ans: 2, diff: 1 },
    { q: "台灣的氣候屬於？", opts: ["溫帶氣候", "亞熱帶與熱帶氣候", "寒帶氣候", "沙漠氣候"], ans: 1, diff: 1 },
    { q: "台灣西部地形多為？", opts: ["山地", "高原", "平原", "盆地"], ans: 2, diff: 1 },
    { q: "中華民國政府現在的首都是？", opts: ["台中", "高雄", "台北", "基隆"], ans: 2, diff: 1 },
    { q: "立法院的主要功能是？", opts: ["執行法律", "制定法律", "解釋法律", "審判案件"], ans: 1, diff: 1 },
    { q: "台灣日治時期最重要的武裝抗日事件之一是？", opts: ["二二八事件", "霧社事件", "白色恐怖", "美麗島事件"], ans: 1, diff: 2 },
    { q: "台灣行政院長由誰任命？", opts: ["立法院", "總統", "監察院", "司法院"], ans: 1, diff: 2 },
    { q: "台灣面積最大的縣市是？", opts: ["台中市", "高雄市", "台南市", "花蓮縣"], ans: 3, diff: 2 },
    { q: "下列哪個不是民主政治的基本原則？", opts: ["主權在民", "法治", "軍事獨裁", "基本人權保障"], ans: 2, diff: 2 },
    { q: "台灣「921大地震」發生在哪一年？", opts: ["1997年", "1998年", "1999年", "2000年"], ans: 2, diff: 2 },
    { q: "台灣主要颱風季節是？", opts: ["1-3月", "4-6月", "7-10月", "11-12月"], ans: 2, diff: 2 },
    { q: "台灣首次總統直選是哪一年？", opts: ["1988年", "1992年", "1996年", "2000年"], ans: 2, diff: 2 },
    { q: "影響台灣氣候最重要的洋流是？", opts: ["親潮", "黑潮", "赤道洋流", "南極洋流"], ans: 1, diff: 2 },
    { q: "台灣割讓給日本後，抵抗的政權稱為？", opts: ["台灣民主國", "台灣共和國", "台灣自治政府", "閩台政府"], ans: 0, diff: 3 },
    { q: "台灣二二八事件發生於哪一年？", opts: ["1945年", "1946年", "1947年", "1948年"], ans: 2, diff: 3 },
    { q: "台灣立法院共有幾席立委（2008年起）？", opts: ["113席", "225席", "164席", "150席"], ans: 0, diff: 3 },
    { q: "聯合國安全理事會常任理事國有幾個？", opts: ["3個", "5個", "7個", "10個"], ans: 1, diff: 3 },
    { q: "「凡爾賽條約」簽訂於哪一年？", opts: ["1917年", "1918年", "1919年", "1920年"], ans: 2, diff: 3 },
  ],

  chinese: [
    // 簡單
    { q: "「囫圇吞棗」的意思是？", opts: ["仔細品嚐", "不求甚解", "慢慢進食", "挑食偏食"], ans: 1, diff: 1 },
    { q: "「一石二鳥」相當於英文的哪個說法？", opts: ["Bite the bullet", "Kill two birds with one stone", "Hit the nail", "Miss the boat"], ans: 1, diff: 1 },
    { q: "「亡羊補牢」後面接的是？", opts: ["為時已晚", "猶未遲也", "無濟於事", "後悔莫及"], ans: 1, diff: 1 },
    { q: "下列哪個字的注音是「ㄇㄣˊ」？", opts: ["門", "問", "聞", "悶"], ans: 0, diff: 1 },
    { q: "「明察秋毫」中的「秋毫」指的是？", opts: ["秋天的稻穗", "秋天動物的細毛", "秋天的落葉", "秋天的天空"], ans: 1, diff: 1 },
    { q: "「狐假虎威」中，狐狸靠什麼嚇退百獸？", opts: ["自己的力量", "借助老虎的威勢", "智慧", "速度"], ans: 1, diff: 1 },
    { q: "「疑」的部首是？", opts: ["匕", "矢", "疋", "匹"], ans: 2, diff: 1 },
    { q: "「破釜沉舟」比喻什麼？", opts: ["準備充分", "下定決心不退縮", "輕鬆取勝", "放棄計畫"], ans: 1, diff: 1 },
    { q: "「魚目混珠」的意思是？", opts: ["魚和珍珠放在一起", "以假冒真", "見多識廣", "眼力很好"], ans: 1, diff: 1 },
    { q: "「塞翁失馬」後面接的是？", opts: ["焉知非福", "何嘗不是好事", "物極必反", "因禍得福"], ans: 0, diff: 1 },
    { q: "「半途而廢」的意思是？", opts: ["努力堅持", "中途放棄", "全力以赴", "猶豫不決"], ans: 1, diff: 1 },
    // 中等
    { q: "李白是哪個朝代的詩人？", opts: ["漢朝", "唐朝", "宋朝", "明朝"], ans: 1, diff: 2 },
    { q: "「人之初，性本善」出自哪本書？", opts: ["論語", "孟子", "三字經", "千字文"], ans: 2, diff: 2 },
    { q: "「四書」不包含下列哪本？", opts: ["論語", "孟子", "詩經", "中庸"], ans: 2, diff: 2 },
    { q: "「溫故知新」出自哪部典籍？", opts: ["孟子", "論語", "老子", "莊子"], ans: 1, diff: 2 },
    { q: "杜甫的詩風格通常被形容為？", opts: ["飄逸浪漫", "清新自然", "沉鬱頓挫", "豪放粗獷"], ans: 2, diff: 2 },
    { q: "「邯鄲學步」說的是哪個地方的走路方式？", opts: ["邯鄲", "燕國", "齊國", "楚國"], ans: 0, diff: 2 },
    { q: "「朝三暮四」原來說的是用什麼餵養猴子？", opts: ["香蕉", "橡實", "蘋果", "堅果"], ans: 1, diff: 2 },
    { q: "「班門弄斧」中的「班」指的是誰？", opts: ["班固", "魯班", "班超", "班昭"], ans: 1, diff: 2 },
    { q: "「紙上談兵」的主角是誰？", opts: ["廉頗", "白起", "趙括", "李牧"], ans: 2, diff: 2 },
    { q: "「青出於藍」後面接的是？", opts: ["而勝於藍", "而冷於藍", "更勝一籌", "後浪推前浪"], ans: 0, diff: 2 },
    { q: "「千里之行，始於足下」出自何書？", opts: ["論語", "老子", "莊子", "孟子"], ans: 1, diff: 2 },
    // 困難
    { q: "「曲高和寡」的「和」，讀作？", opts: ["ㄏㄜˊ", "ㄏㄜˋ", "ㄏㄨˋ", "ㄏㄨㄢˊ"], ans: 1, diff: 3 },
    { q: "下列哪句詩出自王維？", opts: ["床前明月光", "大漠孤煙直", "春眠不覺曉", "鋤禾日當午"], ans: 1, diff: 3 },
    { q: "「洛陽紙貴」與哪位文學家有關？", opts: ["陶淵明", "左思", "蘇東坡", "歐陽修"], ans: 1, diff: 3 },
    { q: "「浮生若夢，為歡幾何」出自哪位詩人？", opts: ["杜甫", "白居易", "李白", "王維"], ans: 2, diff: 3 },
    { q: "「字」和「詞」的差別，下列哪個說法正確？", opts: ["字即詞，無差別", "詞是由字組成的語言單位", "字比詞大", "詞只有一個字"], ans: 1, diff: 3 },
    // 新增簡單
    { q: "「馬到成功」的意思是？", opts: ["騎馬很快", "事情順利成功", "努力練習", "勤奮耕作"], ans: 1, diff: 1 },
    { q: "「一帆風順」的「帆」是指？", opts: ["風帆", "帆布", "帆船", "以上皆可"], ans: 0, diff: 1 },
    { q: "「雪中送炭」與下列哪個意思相近？", opts: ["錦上添花", "落井下石", "及時幫助", "袖手旁觀"], ans: 2, diff: 1 },
    { q: "「過猶不及」的意思是？", opts: ["做多少算多少", "過頭和不夠都不好", "多做多得", "少做少錯"], ans: 1, diff: 1 },
    // 新增中等
    { q: "「捨本逐末」的「本」指什麼？", opts: ["根本、重要的事", "書本", "本來", "本錢"], ans: 0, diff: 2 },
    { q: "「杞人憂天」出自哪本書？", opts: ["論語", "列子", "莊子", "韓非子"], ans: 1, diff: 2 },
    { q: "「一鳴驚人」說的是哪位君王？", opts: ["齊桓公", "楚莊王", "晉文公", "秦穆公"], ans: 1, diff: 2 },
    { q: "古詩「床前明月光，疑是地上霜」的下一句是？", opts: ["獨坐幽篁裡", "舉頭望明月", "春眠不覺曉", "誰家新燕啄春泥"], ans: 1, diff: 2 },
    { q: "「一葉障目，不見泰山」比喻什麼？", opts: ["眼睛不好", "只見局部不見整體", "泰山很高", "遮掩真相"], ans: 1, diff: 2 },
    // 新增困難
    { q: "「信言不美，美言不信」出自？", opts: ["論語", "老子", "孟子", "莊子"], ans: 1, diff: 3 },
    { q: "「子非魚，安知魚之樂」出自哪部典籍？", opts: ["論語", "老子", "莊子", "列子"], ans: 2, diff: 3 },
    // 國中二年級下學期
    { q: "「畫蛇添足」的意思是？", opts: ["多此一舉", "精益求精", "以假亂真", "欲蓋彌彰"], ans: 0, diff: 1 },
    { q: "「臥薪嚐膽」的主角是？", opts: ["勾踐", "夫差", "范蠡", "伍子胥"], ans: 0, diff: 1 },
    { q: "「鑿壁偷光」的苦讀方式是？", opts: ["挖洞借鄰居的燈光", "偷油燈", "在月光下讀書", "用螢火蟲照明"], ans: 0, diff: 1 },
    { q: "「白日依山盡，黃河入海流」的作者是？", opts: ["李白", "杜甫", "王之渙", "孟浩然"], ans: 2, diff: 1 },
    { q: "「螳臂當車」比喻？", opts: ["勇敢無畏", "不自量力", "奮勇抗敵", "以弱勝強"], ans: 1, diff: 1 },
    { q: "「欲窮千里目，更上一層樓」的意思是？", opts: ["要爬更高的樓", "要看更遠需站更高處", "登樓欣賞風景", "登高自卑"], ans: 1, diff: 1 },
    { q: "「過猶不及」的意思是？", opts: ["做多少算多少", "過頭和不夠都不好", "多做多得", "少做少錯"], ans: 1, diff: 1 },
    { q: "「明喻」修辭法使用的連接詞是？", opts: ["是、為", "好像、如同", "讓、使", "雖然、但是"], ans: 1, diff: 2 },
    { q: "「春蠶到死絲方盡，蠟炬成灰淚始乾」的作者是？", opts: ["李白", "杜甫", "李商隱", "白居易"], ans: 2, diff: 2 },
    { q: "「對偶」修辭法的特色是？", opts: ["前後句字數和結構相稱", "用誇張手法描述", "模擬聲音", "反問而不需回答"], ans: 0, diff: 2 },
    { q: "「知己知彼，百戰不殆」出自？", opts: ["論語", "孫子兵法", "老子", "韓非子"], ans: 1, diff: 2 },
    { q: "「頂真」修辭法的特色是？", opts: ["首尾呼應", "前句末字是後句首字", "反覆使用相同詞語", "連用多個比喻"], ans: 1, diff: 2 },
    { q: "「歸去來辭」的作者是？", opts: ["蘇軾", "陶淵明", "李白", "杜甫"], ans: 1, diff: 2 },
    { q: "「借代」修辭法是以？", opts: ["相關事物代替本體", "相似事物比喻本體", "誇大描述", "縮小描述"], ans: 0, diff: 2 },
    { q: "韓愈「文以載道」強調文章應？", opts: ["追求音樂美", "傳達道德思想", "注重押韻", "短小精幹"], ans: 1, diff: 2 },
    { q: "「桃花源記」的作者是？", opts: ["王羲之", "陶淵明", "謝靈運", "劉禹錫"], ans: 1, diff: 3 },
    { q: "「先天下之憂而憂，後天下之樂而樂」出自哪篇文章？", opts: ["出師表", "岳陽樓記", "醉翁亭記", "赤壁賦"], ans: 1, diff: 3 },
    { q: "「設問」和「反問」的差異在於？", opts: ["設問自問自答，反問無須回答", "兩者都不需要回答", "反問需要答案，設問不需要", "完全相同"], ans: 0, diff: 3 },
    { q: "《詩經》「風雅頌」中，「風」是指？", opts: ["宮廷音樂", "祭祀歌曲", "各地民歌", "文人創作"], ans: 2, diff: 3 },
    { q: "「醉翁亭記」作者歐陽修屬於哪個文學運動的代表？", opts: ["浪漫主義", "古文運動", "桐城派", "公安派"], ans: 1, diff: 3 },
  ],

  joke: [
    // 腦筋急轉彎 / 冷笑話（全部 diff:1，輕鬆答題）
    { q: "什麼狗不會叫？", opts: ["老狗", "熱狗", "野狗", "小狗"], ans: 1, diff: 1 },
    { q: "數學課本為什麼總是不開心？", opts: ["太難了", "滿是「問題」", "沒有圖片", "太重了"], ans: 1, diff: 1 },
    { q: "什麼東西越洗越髒？", opts: ["手", "碗", "水", "衣服"], ans: 2, diff: 1 },
    { q: "左邊一個「狗」，右邊一個「狗」，中間是什麼？", opts: ["大狗", "骨頭", "夠了！", "狗窩"], ans: 2, diff: 1 },
    { q: "什麼車不用加油也不用充電？", opts: ["電動車", "太陽能車", "腳踏車", "氫氣車"], ans: 2, diff: 1 },
    { q: "為什麼0不受歡迎？", opts: ["什麼都沒有", "太圓滑了", "它是偶數", "被8包圍了"], ans: 3, diff: 1 },
    { q: "一個人從10樓跳下，為什麼沒事？", opts: ["掉進游泳池", "他是超人", "從一樓門口跳出去的", "穿了降落傘"], ans: 2, diff: 1 },
    { q: "先有雞還是先有蛋？", opts: ["先有雞", "先有蛋", "同時出現", "這是個冷笑話，跳過！"], ans: 3, diff: 1 },
    { q: "程式設計師老婆說：「買一瓶牛奶，看到雞蛋就買一打。」他買了幾瓶牛奶？", opts: ["1瓶", "6瓶", "12瓶", "沒買"], ans: 2, diff: 1 },
    { q: "為什麼程式設計師分不清Halloween和Christmas？", opts: ["節日都很像", "都要吃糖", "OCT 31 = DEC 25（八進制）", "都是外國節日"], ans: 2, diff: 2 },
    { q: "有一根蠟燭、一個油燈和一個壁爐，只有一根火柴，要先點哪個？", opts: ["蠟燭", "油燈", "壁爐", "火柴"], ans: 3, diff: 1 },
    { q: "為什麼科學家無法信任原子？", opts: ["太小看不見", "因為它們組成一切事物", "因為它們會說謊（make up everything）", "因為它們不穩定"], ans: 2, diff: 1 },
    { q: "什麼東西有嘴卻不能說話？", opts: ["電視", "書", "瓶子", "以上皆是"], ans: 2, diff: 1 },
    { q: "為什麼骷髏不打架？", opts: ["沒有力氣", "因為他們沒有膽（膽量）", "因為太懶了", "骷髏不會動"], ans: 1, diff: 1 },
    { q: "什麼時候1加1不等於2？", opts: ["數學壞掉了", "二進制：1+1=10", "反正冷笑話不用算對", "以上皆是"], ans: 1, diff: 1 },
    { q: "什麼書越讀越有精神？", opts: ["漫畫書", "習題本", "咖啡的書", "鬧鐘說明書"], ans: 2, diff: 1 },
    { q: "什麼魚游得最快？", opts: ["金魚", "電魚（電流）", "旗魚", "鮪魚"], ans: 1, diff: 1 },
    { q: "老師問：「教室裡有30個學生，缺了2個，還剩幾個？」學生答：？", opts: ["28個", "30個", "缺了2個就去找", "沒缺，只是遲到了"], ans: 2, diff: 1 },
    { q: "什麼東西摔不破？", opts: ["玻璃", "雞蛋", "影子", "陶器"], ans: 2, diff: 1 },
    { q: "為什麼書不怕冷？", opts: ["書有封面", "書有很多頁（夾）", "書是紙做的", "書在圖書館"], ans: 1, diff: 1 },
  ],
};

const CATEGORY_NAMES = {
  math: "數學",
  english: "英文",
  science: "自然",
  history: "社會",
  chinese: "國文",
  joke: "冷笑話",
};

const CATEGORY_CLASS = {
  math: "math",
  english: "english",
  science: "science",
  history: "history",
  chinese: "chinese",
  joke: "joke",
};

/**
 * 根據難度取得題目
 * @param {string} category
 * @param {number} difficulty 1~3
 * @returns {object} question
 */
function getQuestion(category, difficulty) {
  const pool = QUESTIONS[category].filter(q => q.diff <= difficulty);
  const weightedPool = pool.flatMap(q => {
    const weight = q.diff === difficulty ? 3 : (q.diff === difficulty - 1 ? 2 : 1);
    return Array(weight).fill(q);
  });
  return weightedPool[Math.floor(Math.random() * weightedPool.length)];
}

/**
 * 隨機取得一個科目
 */
function randomCategory() {
  const cats = Object.keys(QUESTIONS);
  return cats[Math.floor(Math.random() * cats.length)];
}
